import type { Metadata } from "next";
import { Ubuntu } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const ubuntu = Ubuntu({
	variable: "--font-body",
	display: "swap",
	weight: ["500"],
});

const chomsky = localFont({
	src: "../public/fonts/Chomsky.otf",
	variable: "--font-heading",
	display: "swap",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={`${chomsky.variable} ${ubuntu.variable} antialiased`}>{children}</body>
		</html>
	);
}
