import type { Metadata } from "next";
import ThemeRegistry from "./ThemeRegistry";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import { ToastProvider } from "@/contexts/ToastContext";
import { AuthProvider } from "@/contexts/AuthContext";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body>
				<AppRouterCacheProvider>
					<AuthProvider>
						<ThemeRegistry>
							<ToastProvider>
								<Navbar />
								{children}
							</ToastProvider>
						</ThemeRegistry>
					</AuthProvider>
				</AppRouterCacheProvider>
			</body>
		</html>
	);
}
