import type { Metadata } from "next";
import ThemeRegistry from "./ThemeRegistry";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import { ToastProvider } from "@/contexts/ToastContext";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body>
				<ThemeRegistry>
					<ToastProvider>
						<Navbar />
						{children}
					</ToastProvider>
				</ThemeRegistry>
			</body>
		</html>
	);
}
